global using Cinematic_Assets_Management.Models;
global using Cinematic_Assets_Management.DataAccess;
global using Cinematic_Assets_Management.Utility;
global using Cinematic_Assets_Management.ModelsView;
global using Cinematic_Assets_Management.Areas.Admin.Controllers;
